// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectRequirementAPI.Data;

#nullable disable

namespace ProjectRequirementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127164826_InitialSingleTable")]
    partial class InitialSingleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectRequirementAPI.Models.ProjectRequirementFormModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("text");

                    b.Property<string>("BasicDetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("DesignPreferencesJson")
                        .HasColumnType("text");

                    b.Property<bool>("DoYouNeedTrainingForStaff")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductMaintenanceJson")
                        .HasColumnType("text");

                    b.Property<string>("ProjectDetailsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectRequirementForms");
                });
#pragma warning restore 612, 618
        }
    }
}
