// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectRequirementAPI.Data;

#nullable disable

namespace ProjectRequirementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectRequirementAPI.Models.ProjectRequirementFormModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "additional_details");

                    b.Property<string>("BasicDetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("DesignPreferencesJson")
                        .HasColumnType("text");

                    b.Property<bool>("DoYouNeedTrainingForStaff")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "do_you_need_training_for_staff");

                    b.Property<string>("ProductMaintenanceJson")
                        .HasColumnType("text");

                    b.Property<string>("ProjectDetailsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("SysCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "sys_created");

                    b.Property<DateTime?>("SysUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "sys_updated");

                    b.HasKey("Id");

                    b.ToTable("ProjectRequirementForms");
                });
#pragma warning restore 612, 618
        }
    }
}
